### ISSUE TITLE
Crash when try place slice

### ISSUE THREAD

**Issue by olegikoligik** [CreativeMD/LittleTiles#108]
[crash-2018-08-02_11.18.48-client.txt](https://github.com/CreativeMD/LittleTiles/files/2252703/crash-2018-08-02_11.18.48-client.txt)

**Comment by CreativeMD** [comment]
Sorry, but there is nothing I can do about that. This exception is really weird, looks like a mod is replacing the javax library ... I suspect it's the rtm mod, but I couldn't find anything.

It might be a good idea to find out which mod is causing it, because there is nothing I can do from my end, sorry :(

**Comment by Dushess** [comment]
Aaa, it triggered not only by LT doors, I've report it on ngt's twitter and curseforge, no results.

**Comment by CreativeMD** [comment]
I think it would be easily avoidable, but there is nothing I can do about it. I create a vector and that's it ... somehow the javax library is messed up.
