### ISSUE TITLE
Opening and closing doors cause lag spikes

### ISSUE THREAD

**Issue by Trinsdar** [CreativeMD/LittleTiles#110]
![door lag](https://user-images.githubusercontent.com/30245301/43681924-7a2053d2-9830-11e8-8bf9-059231df9168.gif)
I'm having problems uploading my debug log to any paste site right now, so I'll just give you my latest log for now.
https://gist.github.com/Trinsdar/cabd4a0a6d4f7269b154534d60d8bbac

Little Tiles v1.5.0-pre102
Creative core 1.9.25
Minecraft 1.12.2
Forge 14.23.4.2729

**Comment by Trinsdar** [comment]
Is this issue at all related to issue 104?

**Comment by CreativeMD** [comment]
No not really. Can you try out pre104, it might fix your issue.

**Comment by Trinsdar** [comment]
still lags

**Comment by Trinsdar** [comment]
Here's my debug log:
https://gist.github.com/Trinsdar/687f9a436115cc823d78b554926f2d21

**Comment by CreativeMD** [comment]
The problem is that there are many mods which could cause this issue. I know for sure that MoCreatures makes doors rather laggy, but there might be more in your modpack. I don't know why this occurs, but there is nothing I can do about it. If you want to you can test which mod is causing it, but I doubt you want to do it. Or just remove MoCreatures and see if it is better.

**Comment by Trinsdar** [comment]
Yep, mo creatures is the cause
