### ISSUE TITLE
Connected textures on little tiles bug out after loading those for the first time. Reloading chunks via debug screen fixes it. Moving doors light up bright.

### ISSUE THREAD

**Issue by TheRealDadbeard** [CreativeMD/LittleTiles#118]
![2018-08-23_21 37 12](https://user-images.githubusercontent.com/23340600/44548714-30d6ac00-a71f-11e8-96fc-9dcc61fefd0a.png)

Mc 1.12.2
Little Tiles: 1.5.0 pre107

For the doors I have no screenshot. Just when I open them every block of them gets completely bright. seems to be an issue more of two block doors. Have another bigger sliding door that doesn't behaves like that. Happens since the update.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier, your issue is quite a tricky one and I honestly don't know how to fix (the connected texture issue). Minecraft's way of loading tileentities is kinda weird, the blocks don't know if its neighbors. So I will ignore it for now, sorry :(

About the sliding door issue: I haven't changed anything about doors. Keep in mind doors don't block light, so they might end up being completely bright although they should block the sunlight.
