### ISSUE TITLE
Disabling Beds in Recipes?

### ISSUE THREAD

**Issue by Mr-B-l-a-c-k** [CreativeMD/LittleTiles#149]
Would it be terribly difficult to add a config to disable bed creation via Little Recipes?

I did a bit of begging and pleading to include LT in FTB Interactions but the pack devs have beds disabled- would it be possible to disable bed creation somehow?

[Interactions is here.](https://www.reddit.com/r/feedthebeast/comments/azw83r/ftb_interactions_prerelease_announcement_post/)

Thank you!

**Comment by Saereth** [comment]
Pack dev here, we have all beds disabled and sleep disallowed with Justenough dimensions, if people somehow get a normal bed and sleep in it, it blows them up like using it in the nether. beds made from littles tiles bypasses this check. Would it possible to get a config option to disallow the creation of beds with little tiles?

**Comment by CreativeMD** [comment]
If you install IGCM you can disable the bed functionality. You can still craft one, but you won't be able to sleep in it. If that is not enough let me know if you want to have an option to disable crafting beds entirely and whether you want to have an option without IGCM.

**Comment by Saereth** [comment]
we were able to kill off the functionality with just enough dimension which we already had in the pack so it ended up being a non issue, thanks for you response on this, should be fine to close the issue @Mr-B-l-a-c-k or you

**Comment by TeamDman** [comment]
The pack is already towering with over 200 mods, in the spirit of keeping it as optimized as possible it'd be great if it was implemented as a config in Little Tiles rather than requiring a dependency that'd only be used for one feature. Depending on the complexity of the implementation, it'd be neat if they were still craftable for aesthetics, but as long as the sleeping is disableable it would be greatly appreciated!
