### ISSUE TITLE
[Suggestion] Blacklist

### ISSUE THREAD

**Issue by SOL3675** [CreativeMD/LittleTiles#173]
I want blacklist for littletiles to balance modpack.
With little hammer, we can get any harvest level blocks. Harvesting higher tier ores causes players skip the progress.

**Comment by CreativeMD** [comment]
Added an option to configure the highest harvest level which can be obtained via LT. I hope this solves your issue. It will be part of the upcoming pre-release. Can't tell when its ready, because it just keeps taking longer and longer. If you want a temporary solution you can disable being able to harvest vanilla blocks completely (for survival).

**Comment by SOL3675** [comment]
Thanks for your support.
My modpack project takes long time since it's huge (takes 1 year?), so I'll wait for this was implemented.

**Comment by CreativeMD** [comment]
Been added to the newest pre-release which is out now!

**Comment by SOL3675** [comment]
Cool! Thanks for your working!
