### ISSUE TITLE
Particle effects cause severe FPS drops and freezes.

### ISSUE THREAD

**Issue by Powback** [CreativeMD/LittleTiles#193]
Reference photo: ![](http://powback.com/u/9a6d01445fb024cf41106aa8ae6ed657.png)
Running latest 1.12 version on Curse/Twitch.

Blocks such as Sand will spawn particle effects (at incorrect size), which causes the client to freeze, become unresponsive, or at best reduce your fps to less than one.

Turning off all particles solves this issue, and I'm able to play with the usual performance. 

The reference photo is a large area, which took several minutes to process when creating the recepie.

Full photo for scale: 

![](http://powback.com/u/13cabe2f840034a2b68fc9a95408e32b.png)

**Comment by Powback** [comment]
Additionally, you can see that furnaces don't translate well when used in LT. I'm not sure if this could be caused by some other mod.

**Comment by kirokadura** [comment]
Stairs, slabs, chests, furnaces, etc dont work when scaling because LT only works with full blocks. 

Most vanilla block that are used in LT keep their properties, so sand has the same particle effects as the vanilla block.
Since particle size is not scalable even 1 tile will generate as much as a full block, so if you scale down a large area its bound to have multiple tiles and a lot of particles. You will either have to replace the sand with another material or put something below it to block the particles.

**Comment by CreativeMD** [comment]
I will also add an option to disable these vanilla block particles

**Comment by CreativeMD** [comment]
Newest version is out including the config option (you don't have to do anything as it is disabled by default).
