### ISSUE TITLE
Usability suggestions

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#206]
These are some suggestions to make using LittleTiles easier, faster, and/or more intuitive. They were starting to pile up in Discord and Kiro suggested they might be better here where they are less likely to get lost.

---

1. When opening the block selection drop-down, automatically place the cursor in the search box

This would greatly speed up my block changes, in those cases when I don't already have some of the material handy to pick from. I already start typing as soon as I click the drop down out of some misplaced habit, and it just causes chaos and confusion :grin: 

---

2. Adjust slider value with mouse wheel when cursor is anywhere over the slider

Great for making those minute adjustments when you missed the exact value you were looking for.

---

3. Black and white checker background behind the color preview

This would make adding transparency a little more obvious. The current background appears to be black, causing the preview to simply get darker.

(Reported by Silvine)

---

4. Shortcut to reset color/transparency sliders to 255

This could be double-clicking or right-clicking on the preview color or the block image. I noticed that double-clicking on the block image does _something,_ (it makes the UI click noise), but I have no idea what.

The flip side of this is "Oh no, I just spent an hour picking the perfect green and lost it horsing around in the color selection GUI."

---

If you want me to split these into separate issues, let me know. I'm happy to provide more details where I can, as well.

**Comment by Codestian** [comment]
**4. Black and white checker background behind the color preview***

In addition, change the range of the transparency to 0 to 1, similar to how CSS or PhotoShop works.

**5. Measure the number of tiles**

Helps to speed up calculating distances between 2 points, as tiles don't always follow the default 16x16 grid. Would work similarly to WorldEdit, where a player crafts a tool (probably a ruler/measuring tape).

To initiate start point, use left click with the tool. To initiate end point, use right click with the tool. The total  number of tiles calculated will automatically be outputted to the console as: 'Number of tiles calculated: ${NUM}'

**6. Allow more options to choose colors from**

Currently, the only way to choose colors is to use RGBA. More options allow players to quickly copy and paste their desired colors.

- a) Color picker
- Players can press a button in the GUI to enable color picker mode, where the player can move around the world and right click anywhere to select the color.
- 
- b) HEX colors
- Have an input where players can copy and paste HEX colors such as #00FF00. Examples of color palettes using HEX colors is [Material Design](https://material.io/design/color/ ).
- 
- c) HSLA colors
- Alternative to RGBA.

**Instead of pressing c once, hold c to open the GUI**

This would work similarly to Chisel & Bits, where the player must hold Alt to open the GUI. Much faster as the player does not need to drag the mouse to close the GUI.

**Comment by kirokadura** [comment]
A little input on some of the suggestions:

**2. Color selection:** if you right click on the slider, you can type in the exact value, which is much more precise.

**5. Measuring tool:** Already planned.

**6. About the color picker:** there's no easy (or feasible) way to select color from a texture ingame. It would also have to take into account the brightness levels, different resource packs, transparency, etc.

**Holding C to open the GUI:** if we did this, things like naming structures and searching for blocks wouldn't be possible, as you won't be able to type properly while holding C. It would be an inconvinience for any other buttons too. It's not an issue with C&B because it's just changing modes.

**Comment by QBFreak** [comment]
**2. Color selection slider:**

It would be nice if Numpad Enter would apply the typed value in addition to Enter and clicking outside of the slider (the current method). I realize this is a WIBNIF (Wouldn't It Be Nice If...), but when I'm dealing with numbers the numpad is what I reach for.

**4. Transparency range**

Sylvine's suggestion to change transparency range from `0-255` to `0-1` would probably be a bit of a change for some users. I would suggest making this a configuration option that defaults to the current method so that users don't have to learn a new way to interact with it if unless they wish to.

**Comment by CreativeMD** [comment]
1. You already did that
2. I added the ability to use the mouse wheel (if you hold ctrl it will move it further). You can use the number pad (tested it myself).
3. Added an image in the background (http://www.secretdoors.com/playit/resources/chessboard.gif) now it's similar to image editors.
4. I don't think the range matters that much. I would rather not change it.
5+6. Kiro already explained those.

I will upload the pre-release now. Thank you very much for all your suggestions. Those little things matter a lot! Hope you can understand why certain things will not be implemented.
