### ISSUE TITLE
Tooltip Displays Below JEI

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/LittleTiles#217]
Minecraft 1.12.2
Forge v14.23.5.2838
Little Tiles v1.5.0-pre151

I noticed that in the Little Bag, tooltips of items render below the JEI menu.
![2019-07-28_23 01 21](https://user-images.githubusercontent.com/12000593/62021945-84534480-b18f-11e9-8164-029301972aeb.png)

**Comment by CreativeMD** [comment]
Will be fixed in the next version (hopefully), should be available in a few minutes.

**Comment by WenXin20** [comment]
The tooltips still render below JEI after I updated to LT v1.5.0-pre153 and CC v1.9.57.

**Comment by CreativeMD** [comment]
Sorry, but I don't see a way to fix this. You could report it to the author JEI.

**Comment by mezz** [comment]
JEI renders on the dark background, so it should be below your tooltips (this works on every other gui).
Please check to see you are rendering things in the same order as vanilla and firing the `GuiScreenEvent.BackgroundDrawnEvent`

**Comment by CreativeMD** [comment]
Oh that's interesting, because I don't fire the event at all ([source](https://github.com/CreativeMD/CreativeCore/blob/1.12/src/main/java/com/creativemd/creativecore/common/gui/mc/GuiContainerSub.java#L129)).

I added it again, so it works properly with my gui, @WenXin20 can you test it once more using this version: https://www.dropbox.com/s/42hdn22oi3j4rhh/CreativeCore_v1.9.62_mc1.12.2.jar?dl=1

**Comment by WenXin20** [comment]
Yep, that fixes it!

**Comment by CreativeMD** [comment]
Nice, it's released now.
@mezz Thanks for your help!

**Comment by mezz** [comment]
👍
