### ISSUE TITLE
Chisel Preview with Optifine & Shaders

### ISSUE THREAD

**Issue by AsimRamay** [CreativeMD/LittleTiles#244]
while this is a issue not really a pertinent one, unlike how for other people where the 'bits' disappear/fail to render , my stuff never miss renders but i can't / don't get a preview for the chisel when i have Shaders & Optifine enabled (VBO on , Region render off) - im wondering if there is an option i can change so that i see the preview 

MC: 1.12.2
Forge: 14.23.5.2838
Shaders: BSL
Optifine: HD U E3

**Comment by CreativeMD** [comment]
Maybe that one helps: https://www.youtube.com/watch?v=xRyAbwZUcwk

**Comment by AsimRamay** [comment]
weird , preview lines option doesn't do anything >.> im so confused right now -> as optifine shouldn't effect preview lines as they are opaque 

update: i think its something to do with the Shader
turning Shader off , and keeping Optifine on it works fine 
-> though going through the Shader settings i see nothing that should cause it

**Comment by SlayerTheChikken** [comment]
Shaders in general aren't really designed to account for mods, so anything modded will show up wrong if it doesn't know how to handle it. Galacticraft for example if you go to the moon very few shaders will work properly and the sky will blast different colors.

I have observed that during a certain time of the day in Tekxit 3 that littletiles preview block doesn't show, but other times of the day it will show perfectly with shaders.

I don't think the issue is with littletiles itself but with the shaders, it may be possible to fix on littletiles side of things but should be kept low priority since it's not a littletiles issue specifically.

**Comment by CreativeMD** [comment]
Unfortunately there is nothing I can do about it. Certain shaders work others seem to have issues with it. You should rather report this issue to the shaderpack you are using. They might be able to do something about it.

**Comment by yll1s** [comment]
Is there a shaders working with littletiles without render issues?
