### ISSUE TITLE
Crash with Nested Door Activators

### ISSUE THREAD

**Issue by FoxMcloud5655** [CreativeMD/LittleTiles#250]
Not 100% sure that this is actually what caused the issue, but it's my first intuition, as I hadn't changed anything else about the build I was making.

When creating nested Door Activators, I first copied into an Advanced Recipe 3 of my "Garage Door" structures, which on their own are nested Advanced Doors with 1 Door Activator.  The crash did not happen until I selected the 2nd door in the list of 3 doors within the Advanced Recipe.  This was an attempt at trying to make these 3 doors activate at the same time.

https://paste.dimdev.org/fobeqivuhe.mccrash

**Comment by kirokadura** [comment]
As far as I am aware, you can't make a nested door activator, as it can't be a child. You can make all three doors activate at once with just one activator, so there's really no need to nest them.

**Comment by FoxMcloud5655** [comment]
I realize that I could do that, but I thought that since I can add 3 structures with Door Activators on them to an Advanced Recipe and be able to select them inside the GUI, I'd be able to do it.  Otherwise, I could hop onto a random server that has Little Tiles installed and proceed to crashloop them.

I am a programmer, but I haven't delved into Little Tile source code yet, so please bear with me if I'm incorrect in my assumptions on how the code works.  If it's not an intended feature, then maybe upon creation, a recipe would check if there are any Door Activators inside of the structures it's copying.  If it finds one, then it would disable the option to create a Door Activator out of the currently copied structure.  If not, it allows you to do so.

**Comment by kirokadura** [comment]
Door Activators are a relatively new feature and this specific issue was only first brought up on August 19th by a user on our Discord server. CreativeMD, the developer for the mod, is currently on vacation, so he would only be able to look into this issue when he gets back.

Since I'm not a dev, the best I could do was explain the reasoning behind the crash and offer an alternative solution in the meantime. I can't promise anything with certainty in regards to the possible changes, so we'll have to wait on MD's input.

Similar issues have happen before with crashes related to mishandling and those were fixed, so I'm confident we can work something out. Sorry for the inconvenience.

**Comment by FoxMcloud5655** [comment]
I appreciate the explanation.  I actually only just started working with this mod since yesterday, but I can usually pick up on things pretty quickly.  I may try to resolve the issue myself and submit a pull request, or I can just live with it for now :P

Good mod; appreciate the thought behind high performance and interoperability while keeping it simple for new users.

**Comment by CreativeMD** [comment]
Hey, I'm back from vacation. Doors Activators should be able to be a child in theory. Seems like there is an unexpected issue. I will try to fix it.

**Comment by FoxMcloud5655** [comment]
Awesome.  Couldn't figure out the code myself, so I'm glad it's being addressed.  Thanks for the update!

**Comment by CreativeMD** [comment]
Hope it's fixed now!
