### ISSUE TITLE
[Feature Request] Hopper/Item IO support.

### ISSUE THREAD

**Issue by SlayerTheChikken** [CreativeMD/LittleTiles#275]
I know this has been asked before, but I thought I would give it a shot since this would be an amazing feature, any chance for the ability to extract/input items to storage blocks whether it be with hopper or pipes and such? 

Maybe a possible solution is to introduce your own pipe/hopper type block/tile entity to connect with other mods? That way you can interact in the exact way you want to, without risking another mod interacting incorrectly.. I thought I would give a possible solution instead of just asking, whether or not it's a good thought or not I dunno :P

**Comment by CreativeMD** [comment]
It's on my todo list and has been requested already a couple of times. It's not that easy to do because in LT everything is dynamic and there is no good way to attach other's mods pipes to it. I don't think it will be a feature of 1.5.0, but instead of 1.6.0 (which will be on 1.14 or 1.15). So not in the near future sorry :(
