### ISSUE TITLE
[Question] How complete is LittleTiles?

### ISSUE THREAD

**Issue by ajthemacboy** [CreativeMD/LittleTiles#4]
Sorry I'm making an issue to ask this, but I'm wondering how well supported LittleTiles is compared to Multiblocks in Forge, currently?

Is it usable in modpacks? Are there serious bugs or crashes?

Thanks.

**Comment by CreativeMD** [comment]
Don't feel sorry for that :D

the update 1.0.0 did take a long time, that's why i released a trailer for it. https://youtu.be/iIAaLtCeaVM
It is stable and survival compatible (that was one of the major things in this update).

It can't replace ForgeMultipart with covering cables etc. It's a different mod.
You can build house, add decorations, doors, chairs ... . It doesn't need to be supported (at least for the most part). Also Chisel already fixed some issues and my mod is compatible with their connected textures.

It should be ready for modpacks and there are no serious bugs or crashes (these are already fixed).
Even if you have a lot of tiles it doesn't lower your FPS too much. (does a better job then ForgeMultipart with rendering performance).

Hope i could answer your question :D
