### ISSUE TITLE
Little Tiles Blocks Dissapearing

### ISSUE THREAD

**Issue by MrMapler** [CreativeMD/LittleTiles#620]
This has been happening a lot to me and I've been getting pretty annoyed by it, one time it happened and usually I know it's just a visual bug but when I updated the blocks for them to reappear they just straight-up disappeared and I lost all my progress.

![2021-03-30_17 31 14](https://user-images.githubusercontent.com/79697647/113069809-5bfac500-917e-11eb-88dd-fe931093f1ab.png)

**Comment by CreativeMD** [comment]
First of all, I really hope you have the newest version of CreativeCore and LittleTiles installed.

1. Is this just a visual thing, or are the tiles really gone?
2. There is a chunk size limit. Unfortunately minecraft has a limit which a saved chunk must not exceed, so if this happens the entire chunk will not be saved and everything after the last successful save attempt is lost.

**Comment by MrMapler** [comment]
Yes I do have the newest version, I know it's a visual glitch, but one time I wasn't just visual. Every time this happens I just update the blocks and upon doing that they will come back, But that one time It happened I updated the blocks and then they didn't come back, I reloaded the world and the blocks that I updated were gone. Do you know of any fixes that I can do on my end while I wait for another version where this glitch is fixed?

**Comment by CreativeMD** [comment]
This is a vanilla issue and won't be fixed in 1.12. 1.16 claims to have fixed it, so I really hope things work better than. For now I can't do anything about it. You have to use less tiles if you don't want to run into it again.
There is no hard limit as the storage size can vary, but I think at around 3-5 million tiles in one chunk the limit is reached.

I will close this issue for now, as I don't see a way to help you in 1.12.
