### ISSUE TITLE
Survival is broken

### ISSUE THREAD

**Issue by MichelJonkman** [CreativeMD/LittleTiles#68]
In the latest version on the curseforge website (v1.5.0-pre51) there are a lot of bugs which basically break the mod in survival. Some of the ones I have come across:
- Rubber mallet not working
- Can't break tiles without using the hammer
- Can't craft any structures from a recipe

It might be a good idea to do a full pass of all of the survival features

Also, you can easily pick up any block using the utility knife and the container as if using a silk touch pickaxe. This includes obsidian.

I hope this will help you somewhat and you'll be able to fix them so that I can actually use it in survival :P

**Comment by CreativeMD** [comment]
Currently you need the Little Bag for everything, otherwise the tiles cannot be added to your inventory.

1.5.0 is not ready for survival yet. Most basics things work, but unfortunately nothing further. After i have reworked all tools i will try to focus on survival mode. I already have many things about it on my todo list, but feel free to give more suggestions. I will close this issue for now.

BTW the Rubebr Mallet has been removed (the item still exists but you can't do anything with it).

**Comment by MichelJonkman** [comment]
Ah alright, thank you. I hope you'll be improving this mod a lot as I'm now starting to use it. On a side note, will you ever make the doors redstone compatible? I want to do some fancy stuff with the doors but I'd need redstone for that.

**Comment by Dushess** [comment]
@K1ll3rM
It's already planned. CreativeMD told, it's a part of 1.5.0 update.

**Comment by CreativeMD** [comment]
@K1ll3rM i might come back to you once i have changed some stuff, since desperately need some beta testers for survival mode.

**Comment by MichelJonkman** [comment]
@CreativeMD If you don't mind it being multiplayer. I don't play a lot of Minecraft but I'll happily do it for this mod

**Comment by CreativeMD** [comment]
@K1ll3rM that's nice, multiplayer is even better. I will come back to you once i have something.
