### ISSUE TITLE
FE Permissions with doors/activators

### ISSUE THREAD

**Issue by Jose76Tron** [CreativeMD/LittleTiles#725]
Maybe add compatibility with permissions from ForgeEssentials? Cause right now if you disable use permission the doors bug, it doesn't open, the animation does play the "open" animation, but the door is still closed cause there's the invisible blocks still there.

**Comment by BlizzardLight** [comment]
yeah 
same issue

**Comment by CreativeMD** [comment]
Yeah ... sorry but I won't fix it. I will rewrite this entire door thingy for 1.17. At the moment the client initiates the door opening and does not wait until the server allows it, so the door animation still plays on client side even though they door stays closed. It's not really an issue with FE Permissions, but an overall problem of the mod, which as I said above will be fixed in the next big version.
