### ISSUE TITLE
crash IllegalArgumentException: Cannot get property PropertyInteger

### ISSUE THREAD

**Issue by Chryfi** [CreativeMD/LittleTiles#734]
[crash-2021-08-23_13.05.01-client (1).txt](https://github.com/CreativeMD/LittleTiles/files/7031380/crash-2021-08-23_13.05.01-client.1.txt)

The game crashes when joining the modded server, seems like a lava block is causing it...
(I am not the server owner, I am doing this for them to report something that may need a fix. If you need more information, please tell. According to them in most of the cases it can get fixed by deleting the playerdata as a workaround)

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. Pretty sure it's an incompatibility with another mod. I don't know which one though. I think the only way to find it out is via trail and error in a singleplayer world. The lava block is indeed causing the issue here, but with just Littletiles and CreativeCore installed it should work.

**Comment by CreativeMD** [comment]
I will close this issue for now. It requires trail and error to figure out the incompatible mod, something I can't find the time for at the moment.
