### ISSUE TITLE
So what happen to 1.7.10?

### ISSUE THREAD

**Issue by KarateSnoopy1911** [CreativeMD/LittleTiles#886]
Hi, although clearly LittleTiles has no support for 1.7.10 from reading other issues, it isn't obvious what happed to the development for 1.7.10. I'm curious specifically because of Gregtech New Horizons which voted for adding little tiles in April 26, 2021, I'm finding it demotivating to deal with either janky and clunky LittleTiles in 1.7.10 or _ArchitectureCraft_ (i'll likely choose Architecture and Ztones for base building) so I'm just having a bit of a 'tough' decision in the long-term modpack. Anyways, what was the problem that kept LittleTiles from 1.7.10 development and are the current reasons for 1.7.10 (5th most downloaded of list of versions, making it arguable it was interesting for most 1.7.10 modpacks but too limited without future support) not worth it? (I don't really know about how many 1.7.10 modpacks are relevant...)

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. Back then LittleTiles was not popular at all. Nobody used it. The only reason why it got continued was that I could use it together with another group. Once 1.9 was out I decided to leave 1.7.10 behind and make it more appealing for everybody else to use. Took almost a year and I reworked a lot of stuff behind the scenes. In the past years, especially since LittleTiles has been released for 1.12, people have gone back to try out the version for 1.7.10, which is bare bones in comparison in what there is today. LittleTiles is a massive project. I'm still working on the port from 1.12 to 1.20 for more than 2 years already. My time is limited and that's why I only go forward with minecraft versions and never backwards. If I try to support multiple ones I would properly never get anywhere. I will not go back to 1.7.10 or even 1.12. Focus is on 1.20 till there is a new version. The faster I can finish the port the more minecraft versions will have a proper version to use.

Besides that 1.7.10 also had some big limitations especially when it comes to translucent blocks. I was happy to move on, also the step from 1.7.10 to 1.9 has been one of the biggest on Minecraft's end. The mod is open source, so anyone can continue the version for 1.7.10, but it will not be easy to port features back because it is so different.

Hope that answers your question.
