### ISSUE TITLE
Protection issues with LittleTiles v1.2.0 mc1.7.10.jar

### ISSUE THREAD

**Issue by NotMyFault** [CreativeMD/LittleTiles#95]
We are currently using this version on our 1.7.10 skyblock modpack. If players use the Little Hammer to create blocks, they can place and break them everywhere. On other players islands and in the spawn area.
I'll attach our mod- and plugin list below and hope this issue can get fixed asap, our players really enjoy the mod and we do not want to remove it.

Server version: Thermos 1.7.10-1614.57

`
Plugins (45): CleanroomGenerator, LuckPerms, WorldEdit, CustomList, KeepItems, MsgColor, PlaceholderAPI, ClearLag, DisableDeathMessage, PlugMan, Announcer, WorldBorder, TabRanks, BuycraftX, AJRankFix, Votifier, ConsoleSpamFix, TileManager, ProtocolLib, WorldGuard, HideAndCustomPlugins, ChatReaction, NoModdedItems, MVdWPlaceholderAPI, SignEdit, QueuedCommands, MegaPlayerClear, BanItem, DonorBroadcast, GAListener, Vault, ChestShop, Essentials, NoFlyZone, WhatIsIt, KitAdder, ASkyBlock, ChestCommands, EssentialsChat, EssentialsSpawn, Multiverse-Core, VoidSpawn, AreaShop, HolographicDisplays, CratesPlus
`

![](https://i.imgur.com/5DWpmjs.png)
![](https://i.imgur.com/SshHRsU.png)
![](https://i.imgur.com/R6365nF.png)

This is the modpack I'm talking about https://www.technicpack.net/modpack/voidpack-2.730619

**Comment by mstingl** [comment]
I had the same Problem a while ago.
As CreativeMD does no longer supports 1.7.10 officially, I (with help of CreativeMD) patched the 1.7.10 version, so that protections are respected.

[littletiles-1.1.zip](https://github.com/CreativeMD/LittleTiles/files/2175646/littletiles-1.1.zip)

You can try it, if it works for you with this patched version and let us know, if it works properly.

**Comment by NotMyFault** [comment]
Aight, much appreciated.
