### ISSUE TITLE
Rendering issue on moving entities from the Create mod (1.20.1)

### ISSUE THREAD

**Issue by Cyannax** [CreativeMD/LittleTiles#965]
LittleTiles blocks fail to render when attached to moving entities from the create mod such as mine carts or trains.

Modlist: Create 0.5.1.f, CreativeCore 2.11.26, LittleTiles 1.6.0-pre101

![2024-04-16_14 54 34](https://github.com/CreativeMD/LittleTiles/assets/105517131/36a14e50-9b47-4946-b53e-10d66de9e8d1)
![2024-04-16_14 54 38](https://github.com/CreativeMD/LittleTiles/assets/105517131/e1cf607d-36f8-46c2-a9d4-55be80d9a2fb)

**Comment by CreativeMD** [comment]
Not sure if that fixes it, but could try to install [Create Interactive](https://www.curseforge.com/minecraft/mc-mods/create-interactive)?

**Comment by Cyannax** [comment]
The newest version (1.0.2-beta.1) of Create Interactive for 1.20.1 crashes upon startup

**Comment by CreativeMD** [comment]
Alright, too bad. LittleTiles uses some different ways to render the blocks to enhance performance. That's why Create's way of rendering blocks does not support it. Unfortunately, that is how it is at the moment. This might be changed in the future, not sure when though. It seemed like Create Interactive added a way for LittleTiles stuff to be rendered (at least that's what somebody on discord showed, that's why I asked to test it).

**Comment by dusieq95** [comment]
Well with Create: Interaction it doesn't work too... :/
